// SHC Portal — Firebase client initialization
// Reads window.__SHC_FIREBASE_CONFIG__ (set by portal/firebase-config.js).
// Exposes:
//   window.shcFirebaseAuth  — firebase.auth() instance
//   window.shcDb            — firebase.firestore() instance
//   window.shcStorage       — firebase.storage() instance
//   window.shcFunctions     — firebase.functions() instance
//
// Depends on (loaded before this file):
//   firebase-app-compat.js
//   firebase-auth-compat.js
//   firebase-firestore-compat.js
//   firebase-storage-compat.js
//   firebase-functions-compat.js
//   portal/firebase-config.js  (gitignored; generated by netlify build)
//
// Must be loaded before auth.js and api.js.

(function () {
  'use strict';

  var cfg = window.__SHC_FIREBASE_CONFIG__ || {};

  var required = ['apiKey', 'authDomain', 'projectId', 'storageBucket', 'messagingSenderId', 'appId'];
  var missing = required.filter(function (k) { return !cfg[k]; });

  if (missing.length) {
    console.error(
      'SHC Firebase: configuration is missing or incomplete.\n' +
      'Missing fields: ' + missing.join(', ') + '\n' +
      'For local development: copy portal/firebase-config.js.example to portal/firebase-config.js and fill in your values.\n' +
      'For Netlify: set FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_PROJECT_ID, ' +
      'FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID in Netlify environment variables.'
    );
  }

  firebase.initializeApp(cfg);

  window.shcFirebaseAuth = firebase.auth();
  window.shcDb           = firebase.firestore();
  window.shcStorage      = firebase.storage();
  window.shcFunctions    = firebase.functions();

  // Enable Firestore persistence for offline resilience in the portal SPA
  window.shcDb.enablePersistence({ synchronizeTabs: true }).catch(function (e) {
    // FAILED_PRECONDITION: multiple tabs; UNIMPLEMENTED: browser not supported
    if (e.code !== 'failed-precondition' && e.code !== 'unimplemented') {
      console.warn('Firestore persistence error:', e.code);
    }
  });

  // Point to emulators when running locally (localhost only)
  if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1') {
    var useEmulators = cfg.useEmulators !== false; // default to true on localhost
    if (useEmulators) {
      window.shcFirebaseAuth.useEmulator('http://localhost:9099');
      window.shcDb.useEmulator('localhost', 8080);
      window.shcStorage.useEmulator('localhost', 9199);
      window.shcFunctions.useEmulator('localhost', 5001);
      console.info('SHC: Firebase emulators active.');
    }
  }

})();
