// SHC Portal — Supabase client initialization
// Loads only the public anon key from window.__SHC_CONFIG__.
// The service-role key is never placed here or in any browser JS.
//
// Depends on:
//   <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js"></script>
//   <script src="/portal/config.js"></script>   (gitignored; generated by netlify build)
// Must be included before auth.js and api.js.

(function () {
  'use strict';

  var cfg = window.__SHC_CONFIG__ || {};

  if (!cfg.SUPABASE_URL || !cfg.SUPABASE_ANON_KEY) {
    console.error(
      'SHC: Supabase configuration is missing.\n' +
      'For local development, copy portal/config.js.example to portal/config.js and fill in your values.\n' +
      'For Netlify deployment, set SUPABASE_URL and SUPABASE_ANON_KEY in the Netlify environment variables.'
    );
  }

  window.shcSupabase = window.supabase.createClient(
    cfg.SUPABASE_URL  || '',
    cfg.SUPABASE_ANON_KEY || '',
    {
      auth: {
        autoRefreshToken: true,
        persistSession: true,
        detectSessionInUrl: true,
        storageKey: 'shc_portal_session'
      }
    }
  );

})();
