(function(){
'use strict';
var data={
 units:[
  {n:'Unit A — Longleaf Restoration',ac:118,condition:'Improving',next:'Prescribed burn',date:'Feb 2027',color:'#c9a55f',desc:'Young longleaf stand with wiregrass recovery following midstory reduction.'},
  {n:'Unit B — Mature Pine Flatwoods',ac:164,condition:'Good',next:'Timber cruise',date:'Oct 2026',color:'#64845d',desc:'Mature slash and longleaf pine managed on a three-year fire return interval.'},
  {n:'Unit C — Hardwood Drain',ac:76,condition:'Protected',next:'Invasive follow-up',date:'Sep 2026',color:'#527b70',desc:'Riparian hardwood corridor retained for mast, travel cover, and water protection.'},
  {n:'Unit D — Wildlife Openings',ac:42,condition:'Active',next:'Fall planting',date:'Oct 2026',color:'#b9a55c',desc:'Six managed openings planted for deer, turkey, and seasonal pollinator value.'},
  {n:'Unit E — Pine Thinning Area',ac:190,condition:'Needs action',next:'First thinning',date:'Jan 2027',color:'#7a956b',desc:'Overstocked loblolly stand marked for thinning to improve growth and understory.'},
  {n:'Roads, Ponds & Homestead',ac:50,condition:'Maintained',next:'Road grading',date:'Aug 2026',color:'#8c7968',desc:'Road system, two ponds, equipment area, and residence buffer.'}
 ],
 projects:[
  ['Aug 2026','Road grading and water-control repair','12 miles','Scheduled','$8,400'],
  ['Sep 2026','Cogongrass and privet follow-up','31 acres','Scheduled','$5,580'],
  ['Oct 2026','Fall wildlife-opening planting','42 acres','Planned','$7,350'],
  ['Jan 2027','Unit E first thinning','190 acres','Awaiting Review','Bid pending'],
  ['Feb 2027','Prescribed burn — Units A and B','282 acres','Planned','$9,870'],
  ['Mar 2027','Spring camera survey','12 stations','Planned','$2,500']
 ],
 budgets:[
  [2026,'Invasive control; roads; fall plots',21330,6900,14430],
  [2027,'Thinning support; prescribed fire; surveys',18670,8400,10270],
  [2028,'Timber stand improvement; monitoring',14200,6100,8100],
  [2029,'Prescribed fire; roads; food plots',16750,7200,9550],
  [2030,'Inventory; invasive follow-up; habitat work',12100,4800,7300]
 ]
};
var views={};
function money(n){return n===0?'—':'$'+n.toLocaleString()}
function metric(l,v,s){return '<div class="metric"><small>'+l+'</small><strong>'+v+'</strong><span>'+s+'</span></div>'}
function map(){
 return '<div class="map-wrap"><svg viewBox="0 0 900 520" role="img" aria-label="Oak Hollow Farm management unit map"><rect width="900" height="520" fill="#dce5d7"/><path d="M65 40 L520 28 L825 95 L848 420 L700 480 L255 492 L55 390 Z" fill="#f4f0df" stroke="#263d31" stroke-width="5"/><path d="M70 44 L330 38 L350 230 L70 220 Z" fill="#c9a55f" stroke="#fff" stroke-width="3"/><path d="M330 38 L520 32 L640 68 L600 255 L350 230 Z" fill="#64845d" stroke="#fff" stroke-width="3"/><path d="M640 68 L820 100 L840 415 L700 475 L610 350 L600 255 Z" fill="#527b70" stroke="#fff" stroke-width="3"/><path d="M70 220 L350 230 L390 365 L255 488 L58 386 Z" fill="#7a956b" stroke="#fff" stroke-width="3"/><path d="M350 230 L600 255 L610 350 L390 365 Z" fill="#b9a55c" stroke="#fff" stroke-width="3"/><path d="M390 365 L610 350 L700 475 L255 488 Z" fill="#8c7968" stroke="#fff" stroke-width="3"/><path d="M115 405 Q300 320 490 405 T795 390" fill="none" stroke="#b79b71" stroke-width="12"/><path d="M115 405 Q300 320 490 405 T795 390" fill="none" stroke="#f2e4ca" stroke-width="4" stroke-dasharray="10 8"/><path d="M735 130 Q680 220 755 310 T720 455" fill="none" stroke="#5c9ab5" stroke-width="7"/><circle cx="480" cy="296" r="18" fill="#6b9fb3" stroke="#fff" stroke-width="3"/><g font-family="Arial" font-weight="700" font-size="14" fill="#fff" text-anchor="middle"><text x="205" y="135">UNIT A · 118 AC</text><text x="475" y="145">UNIT B · 164 AC</text><text x="730" y="275">UNIT C · 76 AC</text><text x="470" y="305">UNIT D · 42 AC</text><text x="215" y="340">UNIT E · 190 AC</text><text x="500" y="430">ROADS / PONDS · 50 AC</text></g><g fill="#a5483c" stroke="#fff" stroke-width="2"><circle cx="170" cy="120" r="7"/><circle cx="420" cy="105" r="7"/><circle cx="560" cy="180" r="7"/><circle cx="220" cy="315" r="7"/><circle cx="520" cy="310" r="7"/><circle cx="735" cy="240" r="7"/></g></svg><div class="map-note"><strong>Oak Hollow Farm</strong><br>Baldwin County, Alabama<br>640 managed acres</div><div class="map-legend"><div><i class="swatch" style="background:#c9a55f"></i>Longleaf restoration</div><div><i class="swatch" style="background:#64845d"></i>Mature pine flatwoods</div><div><i class="swatch" style="background:#527b70"></i>Hardwood drain</div><div><i class="swatch" style="background:#b9a55c"></i>Wildlife openings</div><div><i class="swatch" style="background:#7a956b"></i>Pine thinning area</div><div>● Monitoring station &nbsp; <span style="color:#5c9ab5">━</span> Creek</div></div></div>'
}
function heading(t,s){return '<div class="heading"><div><h1>'+t+'</h1><p>'+s+'</p></div><div class="updated">Last updated July 10, 2026</div></div>'}
views.overview=function(){return '<div class="page">'+heading('Property Overview','Oak Hollow Farm · Baldwin County, Alabama · Active management since 2025')+'<div class="metrics">'+metric('Managed Acreage','640','acres across six units')+metric('Plan Progress','68%','toward five-year objectives')+metric('2026 Work','4','treatments completed')+metric('Active Projects','6','one awaiting review')+'</div><div class="callout"><strong>Action requested:</strong> Review the proposed 190-acre first thinning in Unit E. SHC recommends contractor selection by September 15 to hold a January harvest window. <button class="btn" data-go="work" style="float:right">Review project</button></div><div class="grid-2"><div><div class="panel"><div class="panel-head"><h2>Current Management Activity</h2><button class="btn ghost" data-go="work">All work</button></div><div class="panel-body"><div class="task"><i class="dot amber"></i><div><strong>Road grading mobilization</strong><span>Scheduled August 18–21 · 12 miles</span></div><span class="chip blue">Scheduled</span></div><div class="task"><i class="dot"></i><div><strong>Longleaf survival check complete</strong><span>91% survival across 118 acres · July 2</span></div><span class="chip">Complete</span></div><div class="task"><i class="dot red"></i><div><strong>Cogongrass follow-up needed</strong><span>Seven patches remain in Units B and C</span></div><span class="chip gold">Priority</span></div><div class="task"><i class="dot"></i><div><strong>Summer camera survey processed</strong><span>12 stations · 7,840 images reviewed</span></div><span class="chip">Complete</span></div></div></div></div><div><div class="panel"><div class="panel-head"><h2>2026 Budget</h2><button class="btn ghost" data-go="budget">Five-year plan</button></div><div class="panel-body"><div class="budget-line"><span>2026 Contracted Work</span><strong>$21,330</strong></div><div class="budget-line"><span>Predicted EQIP Offset</span><strong>($6,900)</strong></div><div class="budget-line"><span>Projected Landowner Cost</span><strong>$14,430</strong></div><div class="budget-line"><span>Invoiced to Date</span><strong>$6,200</strong></div></div></div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>Objective Progress</h2></div><div class="panel-body"><div class="objective"><div><span>Restore open pine condition</span><strong>72%</strong></div><div class="progress"><i style="width:72%"></i></div></div><div class="objective"><div><span>Control invasive plants</span><strong>81%</strong></div><div class="progress"><i style="width:81%"></i></div></div><div class="objective"><div><span>Improve wildlife openings</span><strong>55%</strong></div><div class="progress"><i style="width:55%"></i></div></div></div></div></div></div><div class="panel"><div class="panel-head"><h2>Management Map</h2><button class="btn ghost" data-go="map">Open full map</button></div>'+map()+'</div></div>'};
views.property=function(){return '<div class="page">'+heading('My Property','Management units, current condition, and the next recommended action')+'<div class="unit-grid">'+data.units.map(function(u){return '<article class="unit" style="border-top:4px solid '+u.color+'"><h3>'+u.n+'</h3><span class="chip">'+u.condition+'</span><p>'+u.desc+'</p><div class="kv"><div><small>ACREAGE</small><strong>'+u.ac+' acres</strong></div><div><small>NEXT WORK</small><strong>'+u.next+'</strong></div><div><small>TARGET DATE</small><strong>'+u.date+'</strong></div><div><small>LAST INSPECTED</small><strong>Jul 2026</strong></div></div></article>'}).join('')+'</div></div>'};
views.work=function(){return '<div class="page">'+heading('Work & Projects','Completed field work, approved projects, and recommendations awaiting review')+'<div class="grid-2"><div class="panel"><div class="panel-head"><h2>Upcoming Work Program</h2></div><div class="table-wrap"><table><thead><tr><th>Timing</th><th>Project</th><th>Scope</th><th>Status</th><th>Estimate</th></tr></thead><tbody>'+data.projects.map(function(p){return '<tr><td>'+p[0]+'</td><td><strong>'+p[1]+'</strong></td><td>'+p[2]+'</td><td><span class="chip '+(p[3]=='Awaiting Review'?'gold':'blue')+'">'+p[3]+'</span></td><td class="money">'+p[4]+'</td></tr>'}).join('')+'</tbody></table></div></div><div class="panel"><div class="panel-head"><h2>Completed Activity</h2></div><div class="panel-body timeline"><div class="event"><h3>Longleaf survival assessment</h3><p>July 2, 2026 · 118 acres · 91% survival</p><span class="chip">Complete</span></div><div class="event"><h3>Summer camera survey</h3><p>June 1–21, 2026 · 12 stations</p><span class="chip">Complete</span></div><div class="event"><h3>Prescribed burn</h3><p>March 8, 2026 · Unit B · 164 acres</p><span class="chip">Complete</span></div><div class="event"><h3>Midstory herbicide treatment</h3><p>October 2025 · Unit A · 118 acres</p><span class="chip">Complete</span></div><div class="event"><h3>Baseline property inventory</h3><p>February 2025 · Entire property</p><span class="chip">Complete</span></div></div></div></div></div>'};
views.wildlife=function(){return '<div class="page">'+heading('Wildlife Analysis','Monitoring results translated into management decisions')+'<div class="metrics">'+metric('Deer Density','28','estimated deer / sq. mile')+metric('Buck : Doe','1 : 2.4','improved from 1 : 3.1')+metric('Turkey Recruitment','2.1','poults per hen observed')+metric('Predator Index','Moderate','coyote activity stable')+'</div><div class="grid-equal"><div class="panel"><div class="panel-head"><h2>Professional Interpretation</h2></div><div class="panel-body"><div class="survey"><h3>Summer Camera Survey — June 2026</h3><p>Body condition is generally good, with improved buck age structure and fawn recruitment. Doe harvest should remain conservative until the fall mast survey confirms available forage.</p></div><div class="survey"><h3>Turkey Brood Survey — May–July 2026</h3><p>Recruitment improved following the 2026 burn. Maintain open brood cover along Unit B roads and delay mowing two wildlife openings until August.</p></div><div class="survey"><h3>Thermal Drone Survey — February 2026</h3><p>Observed deer use concentrated around the Unit C hardwood drain and northern food plots. No evidence of feral hog establishment was found.</p></div></div></div><div class="panel"><div class="panel-head"><h2>Camera Activity by Species</h2></div><div class="panel-body"><div class="bar-row"><span>Deer</span><div class="bar"><i style="width:92%"></i></div><strong>4,218</strong></div><div class="bar-row"><span>Turkey</span><div class="bar"><i style="width:38%"></i></div><strong>612</strong></div><div class="bar-row"><span>Coyote</span><div class="bar"><i style="width:13%"></i></div><strong>84</strong></div><div class="bar-row"><span>Bobcat</span><div class="bar"><i style="width:8%"></i></div><strong>31</strong></div><div class="bar-row"><span>Hogs</span><div class="bar"><i style="width:1%"></i></div><strong>0</strong></div></div></div></div></div>'};
views.budget=function(){var total=0;return '<div class="page">'+heading('Five-Year Contracted Plan & Budget','Annual contracted management, predicted EQIP offset, and projected landowner responsibility')+'<div class="callout"><strong>EQIP planning estimate:</strong> Cost-share figures are preliminary predictions for potentially eligible practices. Funding requires NRCS application, ranking, approval, and certification and is not guaranteed.</div><div class="panel"><div class="panel-head"><h2>2026–2030 Financial Plan</h2><span class="chip blue">Client approved through 2026</span></div><div class="table-wrap"><table><thead><tr><th>Year</th><th>Primary Program</th><th>Total Contracted</th><th>Predicted EQIP Offset</th><th>Landowner Cost</th></tr></thead><tbody>'+data.budgets.map(function(b){return '<tr><td><strong>'+b[0]+'</strong></td><td>'+b[1]+'</td><td class="money">'+money(b[2])+'</td><td class="money">('+money(b[3])+')</td><td class="money"><strong>'+money(b[4])+'</strong></td></tr>'}).join('')+'<tr><td colspan="2"><strong>Five-Year Total</strong></td><td class="money"><strong>$83,050</strong></td><td class="money"><strong>($33,400)</strong></td><td class="money"><strong>$49,650</strong></td></tr></tbody></table></div></div><div class="grid-equal" style="margin-top:18px"><div class="panel"><div class="panel-head"><h2>Annual Contracted Management</h2></div><div class="panel-body">'+data.budgets.map(function(b){return '<div class="bar-row"><span>'+b[0]+'</span><div class="bar"><i style="width:'+(b[2]/220)+'%"></i></div><strong>'+money(b[2])+'</strong></div>'}).join('')+'</div></div><div class="panel"><div class="panel-head"><h2>Five-Year Funding Summary</h2></div><div class="panel-body"><div class="budget-line"><span>Total contracted management</span><strong>$83,050</strong></div><div class="budget-line"><span>Predicted EQIP cost-share</span><strong>($33,400)</strong></div><div class="budget-line"><span>Projected landowner responsibility</span><strong>$49,650</strong></div><p style="font-size:11px;color:var(--muted);margin-top:14px">Actual landowner cost changes if NRCS funding, practice rates, acreage, or approved scope changes.</p></div></div></div></div>'};
views.reports=function(){var r=[['2026 PROPERTY REVIEW','Annual Property Management Review','Updated July 10, 2026 · 28 pages','Current conditions, completed work, findings, photographs, and next-year priorities.'],['WILDLIFE SURVEY','Summer Camera Survey Report','Published July 1, 2026 · 19 pages','Population estimates, age structure, recruitment, and harvest recommendations.'],['PRESCRIBED FIRE','Unit B Burn Report','Published March 15, 2026 · 12 pages','Weather, ignition pattern, fire behavior, results, and post-burn photographs.'],['MAP BOOK','Oak Hollow Management Map Book','Updated June 2026 · 8 maps','Property boundary, management units, roads, monitoring stations, and treatment history.'],['TIMBER','2025 Forest Inventory','Published March 2025 · 34 pages','Stand conditions, basal area, volume estimates, and thinning recommendations.'],['MANAGEMENT PLAN','Five-Year Management Plan','Approved April 2025 · 42 pages','Objectives, sequence of work, performance measures, and projected budget.']];return '<div class="page">'+heading('Reports & Files','Published plans, surveys, maps, treatment records, and client documents')+'<div class="report-grid">'+r.map(function(x){return '<article class="report"><span class="type">'+x[0]+'</span><h3>'+x[1]+'</h3><div class="meta">'+x[2]+'</div><p>'+x[3]+'</p><button class="btn ghost" onclick="alert(\'Demo report preview — the active portal would open the published PDF.\')">Preview report</button></article>'}).join('')+'</div></div>'};
views.photos=function(){var p=[['Longleaf survival inspection','Unit A · July 2, 2026'],['Prescribed burn results','Unit B · March 15, 2026'],['Thermal drone survey','Unit C · February 18, 2026'],['Wildlife opening growth','Opening 4 · June 24, 2026'],['Cogongrass follow-up point','Unit C · July 7, 2026'],['Road drainage inspection','South access road · July 7, 2026']];return '<div class="page">'+heading('Field Photos','Geotagged documentation from SHC inspections and field work')+'<div class="photo-grid">'+p.map(function(x){return '<article class="photo"><div class="photo-art"><strong>'+x[0]+'</strong></div><div class="photo-info"><strong>'+x[0]+'</strong><span>'+x[1]+'</span></div></article>'}).join('')+'</div></div>'};
views.map=function(){return '<div class="page">'+heading('Property Map','Management units, treatment areas, roads, water, and monitoring locations')+'<div class="panel">'+map()+'</div><div class="panel" style="margin-top:18px"><div class="panel-head"><h2>Visible Layers</h2></div><div class="panel-body"><span class="chip">Property boundary</span> <span class="chip">Management units</span> <span class="chip blue">Roads</span> <span class="chip blue">Water</span> <span class="chip gold">Monitoring stations</span><p style="font-size:12px;color:var(--muted)">In the active portal, this panel can be replaced with an ArcGIS web map so clients can zoom, switch layers, inspect units, and view treatment records spatially.</p></div></div></div>'};
function render(v){document.querySelectorAll('#nav button').forEach(function(b){b.classList.toggle('active',b.dataset.view===v)});document.getElementById('content').innerHTML=(views[v]||views.overview)();document.querySelectorAll('[data-go]').forEach(function(b){b.onclick=function(){render(b.dataset.go)}});window.scrollTo(0,0);if(innerWidth<801)document.getElementById('sidebar').classList.remove('open')}
document.querySelectorAll('#nav button').forEach(function(b){b.onclick=function(){render(b.dataset.view)}});
document.getElementById('menu').onclick=function(){document.getElementById('sidebar').classList.toggle('open')};
render('overview');
})();